path_home: "{{ ansible_user_dir }}"
path_golang: "{{ path_home }}/.golang" # GOPATH
path_nnn_bms: "{{ path_home }}/.config/nnn/bookmarks"

path_projects: "{{ path_home }}/Projects"
path_dotfiles: "{{ path_projects }}/Dotfiles"

git_dockerfiles: https://github.com/ggustafsson/Dockerfiles.git
git_dotfiles: https://github.com/ggustafsson/Dotfiles.git
git_godis: https://github.com/ggustafsson/godis.git
git_kjell: https://github.com/ggustafsson/Kjell.git
git_projectassets: https://github.com/ggustafsson/Project-Assets.git
git_pyttipanna: https://github.com/ggustafsson/Pyttipanna.git
